---
layout: post
title:  python3使用pymongo出现的错误
date:   2019/06/14 11:07
categories:    程序开发
tags: 报错分析 python mongodb 
excerpt: 在使用python3连接mongodb时出现的错误  在程序中连接数据库，出现以下错误  pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused   错误是mongodb数据库没有启动，无法连接到数据库，有时候我们已经启动了数据库，出现这个错误是你的数据库出错退出了  返
comment: true
---
* content
{:top}

<h2>在使用python3连接mongodb时出现的错误</h2>

在程序中连接数据库，出现以下错误

<pre><code class="language-shell ">pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
</code></pre>

错误是mongodb数据库没有启动，无法连接到数据库，有时候我们已经启动了数据库，出现这个错误是你的数据库出错退出了

<h2>返回mongodb数据出现的错误</h2>

由于自己很少使用mongodb数据库，在查询数据库的时候，使用flask的jsonify方法对结果返回时出现了如下的错误：

<pre><code class="language-shell ">TypeError: Object of type 'ObjectId' is not JSON serializable
</code></pre>

包含了对象，因为mongodb数据的<code>_id</code>是一个对象属性。通过转换数据的类型，把结果转换为list，然后在使用jsonify方法返回数据
    